sudo: required
git:
  depth: false
services:
- docker
language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_41b957b188c7_key -iv $encrypted_41b957b188c7_iv -in .netrc.enc -out .netrc -d
- git clone https://github.com/pkoniu/iosr-2017-deployment.git
- sh iosr-2017-deployment/before_install.sh
install:
- npm install
before_script:
- npm test
script:
- sh iosr-2017-deployment/script.sh
after_success:
- sh iosr-2017-deployment/after_success.sh
env:
  global:
  - DOCKER_USER=iosr2017
  - DOCKER_REPO=payments
  - HEROKU_APP_NAME=iosr2017payments
  - secure: OxhnwswRwWlj1Qmn0CtQOjwiWJ/yJv/Y94dyC4tc4uCwubWS52LTAsqG71qUEtWcyCHD8PrzPV2xE/r12q4rHtaroE9oDIfi2uaED6Wp7h9/9wR8L95mhQ2qblWqhDZCW0a6ef4qtufVnO31eQNgE7PXCLdGxDDsgbkyEt+aRToIFoTMx5nu59rur4HGzJYWg4ucTaa1oG3t08lrT+fQchVX050XtPYbh9cCAho0yJnjNrRNz8zeJs4k7G+zYP4ZKXJFFXzBSJ658SOKm9CsyjKN1d/8qX/w19nStgH2xdLn+kP0dMpATqeX4MIygdg4L+BD7BYGdVjSOTrGFPA1PNnRTw5X3HYVDZ/shOzc76FnVAvXnMC4/0KQZf9/Dbyu9hk8Q1Bc61dfnEryTmAuKpusc5BRw8Ol7WpFsw5OygWa4tx0T7Ethvz+24Vn/scHyMrphu4fh/N4nb/aMeXsB+8sH1PazSfve93iH9YXFpAl/jw4jBZg53xtTVK0aW6r8p37Rm7gEf8mBIG9YTqyH6V4MCDbfS9TTeHp/EEzXaQ5jrH3KuEP1epSSMHV7n7f9h0s6KnFQbf3/tn9P2Y3pAcCIJHj3T9sS4qQRGJ7sqgFRlKkyTJXvhISTjSykFZDhvU/b7uXId65IJDLvRHDSMhXMDCjHKaa0FD5Cml2oQo=
  - secure: JBU7c0MpPqNi5ojk3TFKxMXmCUk0zYdTlVvIN4RKXRf9dOd650dA/8jpd+uHKwVmuNA/ovgjmEbvaETd8Kh/Xfv5CEiqfbB71rCQPf+QmgQHhGUgMS4iUpwUbfuxASLY1+f+DJQuZC54BjSnC/pMGYKX/eiM5PE1nc6iWQaKwFUEhxUugRD3QeqB41471Fzs53Y47/UBR9YBCixP2pKIoRirv3Kuwpk7+ZdUdOGMQeS5bIKVuu7hZqPMlTzb1ibxQviYhgiQioAwKmnjmrOWil3kOHMaduuJ2oItqGx2ug90D7Y1tQtY0ncQ7eUvkPvoIaTi/BnvIUxwJ+3pgIVHaVuvIcH4EKdczEyfv3+u+okX9krmDhE7f6Wz2ZhJBOImkocSU8ok2R8j4OhuoT6XrPqks4wCL1KhJ4mOSkWi+l9+h24pEJXzZqW/SRyJpga0LEramRtPfjaoRPxasSIkcnjthg0UY+d2CVlwsjM62wjxISqHPw3fyK5BO8JtU2e8nNbCC/XZAXpE8fjg7Ll/3Eev7++I2AJX2wKZVcbcEXClAMX+NWJmoCmWogIfpsecR+48h4KLNlKh5SLJE9c/FxZ/ke5uwl62Tlpt2/Y+59SC9hXvv/9sxeckodetAATFv+7r3d9rz7nZgPS/WKCVn1PD2GaT9TgGA23iCYKuL6w=
